CREATE TB_ACTIVOMOVIMIENTO
USE TB_ACTIVOMOVIMIENTO
APPEND BLANK
REPLACE FIELD_NAME WITH "IDMOVIMIENTO"
REPLACE FIELD_TYPE WITH "N"
REPLACE FIELD_LEN WITH 9
APPEND BLANK
REPLACE FIELD_NAME WITH "SERIE"
REPLACE FIELD_TYPE WITH "C"
REPLACE FIELD_LEN WITH 25
APPEND BLANK
REPLACE FIELD_NAME WITH "IMEI"
REPLACE FIELD_TYPE WITH "C"
REPLACE FIELD_LEN WITH 18
APPEND BLANK
REPLACE FIELD_NAME WITH "TB_MARCA-IDMARCA"
REPLACE FIELD_TYPE WITH "N"
REPLACE FIELD_LEN WITH 9
APPEND BLANK
REPLACE FIELD_NAME WITH "TB_NOVEDAD-IDESTADO"
REPLACE FIELD_TYPE WITH "N"
REPLACE FIELD_LEN WITH 9
APPEND BLANK
REPLACE FIELD_NAME WITH "TB_USUARIO-IDEMPLEADO"
REPLACE FIELD_TYPE WITH "N"
REPLACE FIELD_LEN WITH 9
APPEND BLANK
REPLACE FIELD_NAME WITH "TB_FACTURA_REMITO-IDFACTURAREMITO"
REPLACE FIELD_TYPE WITH "N"
REPLACE FIELD_LEN WITH 9
APPEND BLANK
REPLACE FIELD_NAME WITH "TB_FACTURA_REMITO-FECHA_COMPRA"
REPLACE FIELD_TYPE WITH "D"
APPEND BLANK
REPLACE FIELD_NAME WITH "FINDEGARANTIA"
REPLACE FIELD_TYPE WITH "D"
APPEND BLANK
REPLACE FIELD_NAME WITH "NOTA"
REPLACE FIELD_TYPE WITH "C"
REPLACE FIELD_LEN WITH 254
APPEND BLANK
REPLACE FIELD_NAME WITH "FECHA_ULTIMO_MOVIMIENTO"
REPLACE FIELD_TYPE WITH "D"
APPEND BLANK
REPLACE FIELD_NAME WITH "TB_OPERADOR-IDOPERADOR"
REPLACE FIELD_TYPE WITH "N"
REPLACE FIELD_LEN WITH 9
APPEND BLANK
CLOSE
RETURN

